### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by baoga1124** [wbojczuk/facebook-group-member-scraper#1]
Hello I'm new, what should i fill in regex! Could you help me, pls!

**Comment by wbojczuk** [comment]
Use (term|another term) and so on

**Comment by baoga1124** [comment]
Thanks, but i not good at coding, can you specific for me!
so, i want to extract UID member from group, i should use (UID) right?
Thanks you very much.

**Comment by wbojczuk** [comment]
This is more of a personal project. Not necessarily a kept-up public repo. I don’t really have the time to create a full length tutorial. Sorry
